#ifndef __ERVP_HBC1_COMMON_MEMORYMAP_OFFSET_H__
#define __ERVP_HBC1_COMMON_MEMORYMAP_OFFSET_H__



// total
#define BW_MMAP_OFFSET_ERVP_HBC1_COMMON None
#define ERVP_HBC1_COMMON_ADDR_INTERVAL 8
#define BW_UNUSED_ERVP_HBC1_COMMON 3
#define NUM_ERVP_HBC1_COMMON_SUBMODULE 0

// reg hbc_header
#define BW_HBC_HEADER 3
#define HBC_HEADER_TYPE_CONTROL 0
#define HBC_HEADER_TYPE_DATA 1
#define HBC_HEADER_TYPE_MULTICAST 2
#define HBC_HEADER_TYPE_BROADCAST 3
#define HBC_HEADER_FRAME_NORMAL 0
#define HBC_HEADER_FRAME_BEACON 1
#define HBC_HEADER_MODE_NORMAL 0
#define HBC_HEADER_MODE_BURST 1
#define HBC_HEADER_111KBPS 0
#define HBC_HEADER_200KBPS 1
#define HBC_HEADER_333KBPS 2
#define HBC_HEADER_1MPS 3
#define HBC_HEADER_89_9KBPS 4
#define HBC_HEADER_161_9KBPS 5
#define HBC_HEADER_269_8KBPS 6
#define HBC_HEADER_809_5KBPS 7

#endif