#ifndef __ERVP_HBC1_TX_MEMORYMAP_H__
#define __ERVP_HBC1_TX_MEMORYMAP_H__

#include "platform_info.h"
#include "ervp_hbc1_tx_memorymap_offset.h"

#define MMAP_SUBMODULE_HTX_MODULATOR (HBC1_TX_BASEADDR+SUBMODULE_ADDR_ERVP_HBC1_TX_HTX_MODULATOR)
#define MMAP_SUBMODULE_HTX_FRAME (HBC1_TX_BASEADDR+SUBMODULE_ADDR_ERVP_HBC1_TX_HTX_FRAME)

// submodule htx_modulator
#define MMAP_HTX_MODULATOR_SW_RESET (HBC1_TX_BASEADDR+MMAP_OFFSET_HTX_MODULATOR_SW_RESET)
#define MMAP_HTX_MODULATOR_VERSION (HBC1_TX_BASEADDR+MMAP_OFFSET_HTX_MODULATOR_VERSION)
#define MMAP_HTX_MODULATOR_CONFIG (HBC1_TX_BASEADDR+MMAP_OFFSET_HTX_MODULATOR_CONFIG)
#define MMAP_HTX_MODULATOR_NUM_VACANT_BUFFERS (HBC1_TX_BASEADDR+MMAP_OFFSET_HTX_MODULATOR_NUM_VACANT_BUFFERS)
#define MMAP_HTX_MODULATOR_STATUS (HBC1_TX_BASEADDR+MMAP_OFFSET_HTX_MODULATOR_STATUS)
#define MMAP_HTX_MODULATOR_TRANSFER_FRAME (HBC1_TX_BASEADDR+MMAP_OFFSET_HTX_MODULATOR_TRANSFER_FRAME)

// submodule htx_frame
#define MMAP_HTX_FRAME_CLEAR (HBC1_TX_BASEADDR+MMAP_OFFSET_HTX_FRAME_CLEAR)
#define MMAP_HTX_FRAME_HEADER (HBC1_TX_BASEADDR+MMAP_OFFSET_HTX_FRAME_HEADER)
#define MMAP_HTX_FRAME_DATA_INPUT (HBC1_TX_BASEADDR+MMAP_OFFSET_HTX_FRAME_DATA_INPUT)

// reg htx_modulator.status
// BW_HTX_MODULATOR_STATUS 1
// HTX_MODULATOR_STATUS_IDLE 0
// HTX_MODULATOR_STATUS_BUSY 1

// reg htx_modulator.sw_reset
// BW_HTX_MODULATOR_SW_RESET 1

// reg htx_modulator.version
// BW_HTX_MODULATOR_VERSION 32

// reg htx_modulator.config
// BW_HTX_MODULATOR_CONFIG 1

// reg htx_modulator.num_vacant_buffers
// BW_HTX_MODULATOR_NUM_VACANT_BUFFERS 32

// reg htx_modulator.transfer_frame
// BW_HTX_MODULATOR_TRANSFER_FRAME 1

// reg htx_frame.clear
// BW_HTX_FRAME_CLEAR 1

// reg htx_frame.header
// BW_HTX_FRAME_HEADER 32

// reg htx_frame.data_input
// BW_HTX_FRAME_DATA_INPUT 32

#endif