#ifndef __ERVP_FLORIAN_MEMORYMAP_H__
#define __ERVP_FLORIAN_MEMORYMAP_H__

#include "platform_info.h"
#include "ervp_florian_memorymap_offset.h"


// submodule florian
#define MMAP_FLORIAN_INPUT (MMAP_SUBMODULE_FLORIAN+MMAP_OFFSET_FLORIAN_INPUT)
#define MMAP_FLORIAN_OUTPUT (MMAP_SUBMODULE_FLORIAN+MMAP_OFFSET_FLORIAN_OUTPUT)
#define MMAP_FLORIAN_OUTPUT_VALID_NUM (MMAP_SUBMODULE_FLORIAN+MMAP_OFFSET_FLORIAN_OUTPUT_VALID_NUM)

// reg florian.input
// BW_FLORIAN_INPUT 32

// reg florian.output
// BW_FLORIAN_OUTPUT 32

// reg florian.output_valid_num
// BW_FLORIAN_OUTPUT_VALID_NUM 2

// reg florian_op
// BW_FLORIAN_OP 5
// FLORIAN_OP_CONV 1
// FLORIAN_OP_ADD 2
// FLORIAN_OP_SUB 4
// FLORIAN_OP_MULT 8
// FLORIAN_OP_DIV 16
// FLORIAN_OP_INDEX_CONV 0
// FLORIAN_OP_INDEX_ADD 1
// FLORIAN_OP_INDEX_SUB 2
// FLORIAN_OP_INDEX_MULT 3
// FLORIAN_OP_INDEX_DIV 4
// FLORIAN_OP_NONE 0

// reg florian_value_type
// BW_FLORIAN_VALUE_TYPE 2
// FLORIAN_VALUE_TYPE_SI32 0
// FLORIAN_VALUE_TYPE_UI32 1
// FLORIAN_VALUE_TYPE_F32 2
// FLORIAN_VALUE_TYPE_F64 3
// FLORIAN_VALUE_TYPE_INDEX_UI32 0
// FLORIAN_VALUE_TYPE_INDEX_F32 1

// reg florian_state
// BW_FLORIAN_STATE 3
// FLORIAN_STATE_WAIT 0
// FLORIAN_STATE_ARGS 1
// FLORIAN_STATE_CAL 2
// FLORIAN_STATE_NORMALIZE 3
// FLORIAN_STATE_ENCODE 4
// FLORIAN_STATE_RETURN 5
// FLORIAN_STATE_INDEX_ARGS 0
// FLORIAN_STATE_INDEX_CAL 1
// FLORIAN_STATE_INDEX_ENCODE 2

#endif