#ifndef __ERVP_TIMER_MEMORYMAP_OFFSET_H__
#define __ERVP_TIMER_MEMORYMAP_OFFSET_H__



// total
#define BW_MMAP_OFFSET_ERVP_TIMER 6
#define ERVP_TIMER_ADDR_INTERVAL 8
#define BW_UNUSED_ERVP_TIMER 3
#define NUM_ERVP_TIMER_SUBMODULE 1

// submodule timer
#define MMAP_SUBOFFSET_TIMER_CMD 0x0
#define MMAP_SUBOFFSET_TIMER_INTERVAL 0x8
#define MMAP_SUBOFFSET_TIMER_ITR_CLEAR 0x10
#define MMAP_SUBOFFSET_TIMER_DELAY 0x18
#define MMAP_SUBOFFSET_TIMER_ISR 0x20

#define MMAP_OFFSET_TIMER_CMD (MMAP_SUBOFFSET_TIMER_CMD)
#define MMAP_OFFSET_TIMER_INTERVAL (MMAP_SUBOFFSET_TIMER_INTERVAL)
#define MMAP_OFFSET_TIMER_ITR_CLEAR (MMAP_SUBOFFSET_TIMER_ITR_CLEAR)
#define MMAP_OFFSET_TIMER_DELAY (MMAP_SUBOFFSET_TIMER_DELAY)
#define MMAP_OFFSET_TIMER_ISR (MMAP_SUBOFFSET_TIMER_ISR)

// reg timer.cmd
#define BW_TIMER_CMD 5
#define TIMER_CMD_IDLE 9
#define TIMER_CMD_ITR_ONCE 3
#define TIMER_CMD_ITR_PERIODIC 7
#define TIMER_CMD_DELAY 24

// reg timer.interval
#define BW_TIMER_INTERVAL 32

// reg timer.itr_clear
#define BW_TIMER_ITR_CLEAR 32

// reg timer.delay
#define BW_TIMER_DELAY 32

// reg timer.isr
#define BW_TIMER_ISR 32

#endif