#ifndef __ERVP_DMA_MEMORYMAP_H__
#define __ERVP_DMA_MEMORYMAP_H__

#include "platform_info.h"
#include "ervp_dma_memorymap_offset.h"


// submodule dma
#define MMAP_DMA_STATUS (I_DMA_CONTROL_BASEADDR+MMAP_OFFSET_DMA_STATUS)
#define MMAP_DMA_START (I_DMA_CONTROL_BASEADDR+MMAP_OFFSET_DMA_START)
#define MMAP_DMA_PERIOD_INFO (I_DMA_CONTROL_BASEADDR+MMAP_OFFSET_DMA_PERIOD_INFO)
#define MMAP_DMA_SRC_ADDR (I_DMA_CONTROL_BASEADDR+MMAP_OFFSET_DMA_SRC_ADDR)
#define MMAP_DMA_SRC_STRIDE (I_DMA_CONTROL_BASEADDR+MMAP_OFFSET_DMA_SRC_STRIDE)
#define MMAP_DMA_DST_ADDR (I_DMA_CONTROL_BASEADDR+MMAP_OFFSET_DMA_DST_ADDR)
#define MMAP_DMA_DST_STRIDE (I_DMA_CONTROL_BASEADDR+MMAP_OFFSET_DMA_DST_STRIDE)
#define MMAP_DMA_LINE_INFO (I_DMA_CONTROL_BASEADDR+MMAP_OFFSET_DMA_LINE_INFO)

// reg dma.status
// BW_DMA_STATUS 3
// DMA_STATUS_IDLE 0
// DMA_STATUS_START_CHECK 1
// DMA_STATUS_START_ACK 2
// DMA_STATUS_BUSY 3
// DMA_STATUS_WAIT_NEXT 4
// DMA_STATUS_INDEX_START_CHECK 0
// DMA_STATUS_INDEX_START_ACK 1
// DMA_STATUS_INDEX_WAIT_NEXT 2

// reg dma.start
// BW_DMA_START 1

// reg dma.period_info
// BW_DMA_PERIOD_INFO 32

// reg dma.src_addr
// BW_DMA_SRC_ADDR 32

// reg dma.src_stride
// BW_DMA_SRC_STRIDE 32

// reg dma.dst_addr
// BW_DMA_DST_ADDR 32

// reg dma.dst_stride
// BW_DMA_DST_STRIDE 32

// reg dma.line_info
// BW_DMA_LINE_INFO 32

// reg dma_state
// BW_DMA_STATE 2
// DMA_STATE_IDLE 0
// DMA_STATE_RUN_ALL 1
// DMA_STATE_RUN_WCH 2
// DMA_STATE_WAIT 3
// DMA_STATE_INDEX_RUN_ALL 0
// DMA_STATE_INDEX_RUN_WCH 1

// reg dma_line_size
// BW_DMA_LINE_SIZE 16

// reg dma_num_lines
// BW_DMA_NUM_LINES 16

// reg dma_period
// BW_DMA_PERIOD 16

#endif