#ifndef __ERVP_COMMON_PERI_GROUP_MEMORYMAP_H__
#define __ERVP_COMMON_PERI_GROUP_MEMORYMAP_H__

#include "platform_info.h"
#include "ervp_common_peri_group_memorymap_offset.h"

#define MMAP_SUBMODULE_IROM (COMMON_PERI_GROUP_BASEADDR+SUBMODULE_ADDR_ERVP_COMMON_PERI_GROUP_IROM)
#define MMAP_SUBMODULE_LOCK (COMMON_PERI_GROUP_BASEADDR+SUBMODULE_ADDR_ERVP_COMMON_PERI_GROUP_LOCK)
#define MMAP_SUBMODULE_AUTO_ID (COMMON_PERI_GROUP_BASEADDR+SUBMODULE_ADDR_ERVP_COMMON_PERI_GROUP_AUTO_ID)
#define MMAP_SUBMODULE_CPG_MISC (COMMON_PERI_GROUP_BASEADDR+SUBMODULE_ADDR_ERVP_COMMON_PERI_GROUP_CPG_MISC)
#define MMAP_SUBMODULE_REAL_CLOCK (COMMON_PERI_GROUP_BASEADDR+SUBMODULE_ADDR_ERVP_COMMON_PERI_GROUP_REAL_CLOCK)

// submodule irom

// submodule lock

// submodule auto_id

// submodule cpg_misc
#define MMAP_CPG_MISC_GLOBAL_TAG (COMMON_PERI_GROUP_BASEADDR+MMAP_OFFSET_CPG_MISC_GLOBAL_TAG)
#define MMAP_CPG_MISC_SYSTEM_TICK_CONFIG (COMMON_PERI_GROUP_BASEADDR+MMAP_OFFSET_CPG_MISC_SYSTEM_TICK_CONFIG)
#define MMAP_CPG_MISC_CORE_TICK_CONFIG (COMMON_PERI_GROUP_BASEADDR+MMAP_OFFSET_CPG_MISC_CORE_TICK_CONFIG)

// submodule real_clock

// reg cpg_misc.global_tag
// BW_CPG_MISC_GLOBAL_TAG 8

// reg cpg_misc.system_tick_config
// BW_CPG_MISC_SYSTEM_TICK_CONFIG 11

// reg cpg_misc.core_tick_config
// BW_CPG_MISC_CORE_TICK_CONFIG 11

#endif