#ifndef __ERVP_CORE_PERI_GROUP_MEMORYMAP_H__
#define __ERVP_CORE_PERI_GROUP_MEMORYMAP_H__

#include "platform_info.h"
#include "ervp_core_peri_group_memorymap_offset.h"

#define MMAP_SUBMODULE_TIMER (CORE_PERI_GROUP_BASEADDR+SUBMODULE_ADDR_ERVP_CORE_PERI_GROUP_TIMER)
#define MMAP_SUBMODULE_MULTICORE_SUPPORTER (CORE_PERI_GROUP_BASEADDR+SUBMODULE_ADDR_ERVP_CORE_PERI_GROUP_MULTICORE_SUPPORTER)
#define MMAP_SUBMODULE_WAIT_LOCK (CORE_PERI_GROUP_BASEADDR+SUBMODULE_ADDR_ERVP_CORE_PERI_GROUP_WAIT_LOCK)
#define MMAP_SUBMODULE_TCU (CORE_PERI_GROUP_BASEADDR+SUBMODULE_ADDR_ERVP_CORE_PERI_GROUP_TCU)
#define MMAP_SUBMODULE_FLORIAN (CORE_PERI_GROUP_BASEADDR+SUBMODULE_ADDR_ERVP_CORE_PERI_GROUP_FLORIAN)

// submodule timer

// submodule multicore_supporter
#define MMAP_MULTICORE_SUPPORTER_PROCESS_ID (CORE_PERI_GROUP_BASEADDR+MMAP_OFFSET_MULTICORE_SUPPORTER_PROCESS_ID)
#define MMAP_MULTICORE_SUPPORTER_SET_PRIVATE_TAG (CORE_PERI_GROUP_BASEADDR+MMAP_OFFSET_MULTICORE_SUPPORTER_SET_PRIVATE_TAG)
#define MMAP_MULTICORE_SUPPORTER_WAIT_BARRIER (CORE_PERI_GROUP_BASEADDR+MMAP_OFFSET_MULTICORE_SUPPORTER_WAIT_BARRIER)

// submodule wait_lock

// submodule tcu

// submodule florian

// reg multicore_supporter.process_id
// BW_MULTICORE_SUPPORTER_PROCESS_ID 8

// reg multicore_supporter.set_private_tag
// BW_MULTICORE_SUPPORTER_SET_PRIVATE_TAG 8

// reg multicore_supporter.wait_barrier
// BW_MULTICORE_SUPPORTER_WAIT_BARRIER 1

#endif