#ifndef __ERVP_CACHE_MEMORYMAP_OFFSET_H__
#define __ERVP_CACHE_MEMORYMAP_OFFSET_H__



// total
#define BW_MMAP_OFFSET_ERVP_CACHE None
#define ERVP_CACHE_ADDR_INTERVAL 8
#define BW_UNUSED_ERVP_CACHE 3
#define NUM_ERVP_CACHE_SUBMODULE 0

// reg cache_policy
#define BW_CACHE_POLICY 2
#define CACHE_POLICY_READ_ONLY 0
#define CACHE_POLICY_WRITE_THROUGH 1
#define CACHE_POLICY_WRITE_BACK 2
#define CACHE_POLICY_INDEX_WRITE_THROUGH 0
#define CACHE_POLICY_INDEX_WRITE_BACK 1

// reg cache_command
#define BW_CACHE_COMMAND 2
#define CACHE_COMMAND_INITIALIZE 0
#define CACHE_COMMAND_INVALIDATE 1
#define CACHE_COMMAND_FLUSH 2
#define CACHE_COMMAND_CLEAN 3
#define CACHE_COMMAND_INDEX_INVALIDATE 0
#define CACHE_COMMAND_INDEX_FLUSH 1

#endif