#ifndef __ERVP_PLATFORM_CONTROLLER_MEMORYMAP_H__
#define __ERVP_PLATFORM_CONTROLLER_MEMORYMAP_H__

#include "platform_info.h"
#include "ervp_platform_controller_memorymap_offset.h"

#define MMAP_SUBMODULE_RESET (PLATFORM_CONTROLLER_BASEADDR+SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_RESET)
#define MMAP_SUBMODULE_PLATFORM_REGISTER (PLATFORM_CONTROLLER_BASEADDR+SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_PLATFORM_REGISTER)
#define MMAP_SUBMODULE_DESIGN_INFO (PLATFORM_CONTROLLER_BASEADDR+SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_DESIGN_INFO)
#define MMAP_SUBMODULE_EXTERNAL (PLATFORM_CONTROLLER_BASEADDR+SUBMODULE_ADDR_ERVP_PLATFORM_CONTROLLER_EXTERNAL)

// submodule reset
#define MMAP_RESET_CMD (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_RESET_CMD)
#define MMAP_RESET_MASK (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_RESET_MASK)
#define MMAP_RESET_SEQUENCE (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_RESET_SEQUENCE)

// submodule platform_register
#define MMAP_PLATFORM_REGISTER_BOOT_MODE (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_BOOT_MODE)
#define MMAP_PLATFORM_REGISTER_INITIALIZED (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_INITIALIZED)
#define MMAP_PLATFORM_REGISTER_SIM_ENV (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_SIM_ENV)
#define MMAP_PLATFORM_REGISTER_JTAG_SELECT (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_JTAG_SELECT)
#define MMAP_PLATFORM_REGISTER_BOOT_STATUS (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_BOOT_STATUS)
#define MMAP_PLATFORM_REGISTER_APP_ADDR (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_APP_ADDR)
#define MMAP_PLATFORM_REGISTER_PROC_AUTO_ID (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_PROC_AUTO_ID)
#define MMAP_PLATFORM_REGISTER_PROC_STATUS (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_PROC_STATUS)
#define MMAP_PLATFORM_REGISTER_CORE_PC00 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_CORE_PC00)
#define MMAP_PLATFORM_REGISTER_CORE_PC01 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_CORE_PC01)
#define MMAP_PLATFORM_REGISTER_CORE_PC02 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_CORE_PC02)
#define MMAP_PLATFORM_REGISTER_CORE_PC03 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_CORE_PC03)
#define MMAP_PLATFORM_REGISTER_CORE_INST00 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_CORE_INST00)
#define MMAP_PLATFORM_REGISTER_CORE_INST01 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_CORE_INST01)
#define MMAP_PLATFORM_REGISTER_CORE_INST02 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_CORE_INST02)
#define MMAP_PLATFORM_REGISTER_CORE_INST03 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_CORE_INST03)
#define MMAP_PLATFORM_REGISTER_IMP_TYPE (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_IMP_TYPE)
#define MMAP_PLATFORM_REGISTER_FLASH_BASE_ADDR (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_PLATFORM_REGISTER_FLASH_BASE_ADDR)

// submodule design_info
#define MMAP_DESIGN_INFO_DATE00 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_DATE00)
#define MMAP_DESIGN_INFO_DATE01 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_DATE01)
#define MMAP_DESIGN_INFO_DATE02 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_DATE02)
#define MMAP_DESIGN_INFO_DATE03 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_DATE03)
#define MMAP_DESIGN_INFO_DATE04 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_DATE04)
#define MMAP_DESIGN_INFO_DATE05 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_DATE05)
#define MMAP_DESIGN_INFO_DATE06 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_DATE06)
#define MMAP_DESIGN_INFO_DATE07 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_DATE07)
#define MMAP_DESIGN_INFO_USERNAME00 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_USERNAME00)
#define MMAP_DESIGN_INFO_USERNAME01 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_USERNAME01)
#define MMAP_DESIGN_INFO_USERNAME02 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_USERNAME02)
#define MMAP_DESIGN_INFO_USERNAME03 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_USERNAME03)
#define MMAP_DESIGN_INFO_HOME_GIT_NAME00 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_HOME_GIT_NAME00)
#define MMAP_DESIGN_INFO_HOME_GIT_NAME01 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_HOME_GIT_NAME01)
#define MMAP_DESIGN_INFO_HOME_GIT_NAME02 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_HOME_GIT_NAME02)
#define MMAP_DESIGN_INFO_HOME_GIT_NAME03 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_HOME_GIT_NAME03)
#define MMAP_DESIGN_INFO_PLATFORM_NAME00 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_PLATFORM_NAME00)
#define MMAP_DESIGN_INFO_PLATFORM_NAME01 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_PLATFORM_NAME01)
#define MMAP_DESIGN_INFO_PLATFORM_NAME02 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_PLATFORM_NAME02)
#define MMAP_DESIGN_INFO_PLATFORM_NAME03 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_PLATFORM_NAME03)
#define MMAP_DESIGN_INFO_HOME_GIT_VERSION00 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_HOME_GIT_VERSION00)
#define MMAP_DESIGN_INFO_HOME_GIT_VERSION01 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_HOME_GIT_VERSION01)
#define MMAP_DESIGN_INFO_HOME_GIT_VERSION02 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_HOME_GIT_VERSION02)
#define MMAP_DESIGN_INFO_HOME_GIT_VERSION03 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_HOME_GIT_VERSION03)
#define MMAP_DESIGN_INFO_DEVKIT_GIT_VERSION00 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION00)
#define MMAP_DESIGN_INFO_DEVKIT_GIT_VERSION01 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION01)
#define MMAP_DESIGN_INFO_DEVKIT_GIT_VERSION02 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION02)
#define MMAP_DESIGN_INFO_DEVKIT_GIT_VERSION03 (PLATFORM_CONTROLLER_BASEADDR+MMAP_OFFSET_DESIGN_INFO_DEVKIT_GIT_VERSION03)

// submodule external

// reg reset.cmd
// BW_RESET_CMD 3
// RESET_CMD_IDLE 0
// RESET_CMD_INIT 1
// RESET_CMD_AUTO_INCR 2
// RESET_CMD_NEXT_STEP 3
// RESET_CMD_IDLE_WITH_ERROR 4
// RESET_CMD_INDEX_INIT 0
// RESET_CMD_INDEX_AUTO_INCR 1
// RESET_CMD_INDEX_IDLE_WITH_ERROR 2

// reg reset.mask
// BW_RESET_MASK 32

// reg reset.sequence
// BW_RESET_SEQUENCE 32

// reg platform_register.boot_mode
// BW_PLATFORM_REGISTER_BOOT_MODE 4

// reg platform_register.initialized
// BW_PLATFORM_REGISTER_INITIALIZED 1

// reg platform_register.sim_env
// BW_PLATFORM_REGISTER_SIM_ENV 1

// reg platform_register.jtag_select
// BW_PLATFORM_REGISTER_JTAG_SELECT 1

// reg platform_register.boot_status
// BW_PLATFORM_REGISTER_BOOT_STATUS 32

// reg platform_register.app_addr
// BW_PLATFORM_REGISTER_APP_ADDR 32

// reg platform_register.proc_auto_id
// BW_PLATFORM_REGISTER_PROC_AUTO_ID 32

// reg platform_register.proc_status
// BW_PLATFORM_REGISTER_PROC_STATUS 32

// reg platform_register.core_pc
// BW_PLATFORM_REGISTER_CORE_PC 32

// reg platform_register.core_inst
// BW_PLATFORM_REGISTER_CORE_INST 32

// reg platform_register.imp_type
// BW_PLATFORM_REGISTER_IMP_TYPE 32

// reg platform_register.flash_base_addr
// BW_PLATFORM_REGISTER_FLASH_BASE_ADDR 32

// reg design_info.date
// BW_DESIGN_INFO_DATE 32

// reg design_info.username
// BW_DESIGN_INFO_USERNAME 32

// reg design_info.home_git_name
// BW_DESIGN_INFO_HOME_GIT_NAME 32

// reg design_info.platform_name
// BW_DESIGN_INFO_PLATFORM_NAME 32

// reg design_info.home_git_version
// BW_DESIGN_INFO_HOME_GIT_VERSION 32

// reg design_info.devkit_git_version
// BW_DESIGN_INFO_DEVKIT_GIT_VERSION 32

// reg boot_mode
// BW_BOOT_MODE 1
// BOOT_MODE_OCD 0
// BOOT_MODE_STAND_ALONE 1
// BOOT_MODE_INDEX_STAND_ALONE 0

// reg boot_status
// BW_BOOT_STATUS 2
// BOOT_STATUS_RESETED 0
// BOOT_STATUS_APP_LOAD 1
// BOOT_STATUS_ALL_READY 2
// BOOT_STATUS_INDEX_APP_LOAD 0
// BOOT_STATUS_INDEX_ALL_READY 1

// reg jtag_select
// BW_JTAG_SELECT 1
// JTAG_SELECT_NOC 0
// JTAG_SELECT_CORE 1
// JTAG_SELECT_INDEX_CORE 0

// reg imp_type
// BW_IMP_TYPE 2
// IMP_TYPE_RTL 0
// IMP_TYPE_FPGA 1
// IMP_TYPE_CHIP 2
// IMP_TYPE_VP 3
// IMP_TYPE_INDEX_FPGA 0
// IMP_TYPE_INDEX_CHIP 1

#endif