#ifndef __ERVP_I2S_MASTER_MEMORYMAP_H__
#define __ERVP_I2S_MASTER_MEMORYMAP_H__

#include "platform_info.h"
#include "ervp_i2s_master_memorymap_offset.h"


// submodule i2s_master
#define MMAP_I2S_MASTER_CMD (I_I2S_MASTER_SLAVE_BASEADDR+MMAP_OFFSET_I2S_MASTER_CMD)
#define MMAP_I2S_MASTER_STATUS (I_I2S_MASTER_SLAVE_BASEADDR+MMAP_OFFSET_I2S_MASTER_STATUS)
#define MMAP_I2S_MASTER_RX_ITR_NUM (I_I2S_MASTER_SLAVE_BASEADDR+MMAP_OFFSET_I2S_MASTER_RX_ITR_NUM)
#define MMAP_I2S_MASTER_TX_FIFO (I_I2S_MASTER_SLAVE_BASEADDR+MMAP_OFFSET_I2S_MASTER_TX_FIFO)
#define MMAP_I2S_MASTER_RX_FIFO (I_I2S_MASTER_SLAVE_BASEADDR+MMAP_OFFSET_I2S_MASTER_RX_FIFO)
#define MMAP_I2S_MASTER_RX_FIFO_VALID_NUM (I_I2S_MASTER_SLAVE_BASEADDR+MMAP_OFFSET_I2S_MASTER_RX_FIFO_VALID_NUM)

// reg i2s_master.cmd
// BW_I2S_MASTER_CMD 8
// I2S_MASTER_CMD_ENABLE_TX 1
// I2S_MASTER_CMD_DISABLE_TX 2
// I2S_MASTER_CMD_ENABLE_RX 4
// I2S_MASTER_CMD_DISABLE_RX 8
// I2S_MASTER_CMD_ENABLE_RX_ITR 16
// I2S_MASTER_CMD_DISABLE_RX_ITR 32
// I2S_MASTER_CMD_CLEAR_RX_ITR 64
// I2S_MASTER_CMD_CLEAR_STATUS 128
// I2S_MASTER_CMD_INDEX_ENABLE_TX 0
// I2S_MASTER_CMD_INDEX_DISABLE_TX 1
// I2S_MASTER_CMD_INDEX_ENABLE_RX 2
// I2S_MASTER_CMD_INDEX_DISABLE_RX 3
// I2S_MASTER_CMD_INDEX_ENABLE_RX_ITR 4
// I2S_MASTER_CMD_INDEX_DISABLE_RX_ITR 5
// I2S_MASTER_CMD_INDEX_CLEAR_RX_ITR 6
// I2S_MASTER_CMD_INDEX_CLEAR_STATUS 7
// I2S_MASTER_CMD_NONE 0

// reg i2s_master.status
// BW_I2S_MASTER_STATUS 5
// I2S_MASTER_STATUS_TX_ENABLE 1
// I2S_MASTER_STATUS_RX_ENABLE 2
// I2S_MASTER_STATUS_RX_ITR_ENABLE 4
// I2S_MASTER_STATUS_TX_UNDERFLOW 8
// I2S_MASTER_STATUS_RX_OVERFLOW 16
// I2S_MASTER_STATUS_INDEX_TX_ENABLE 0
// I2S_MASTER_STATUS_INDEX_RX_ENABLE 1
// I2S_MASTER_STATUS_INDEX_RX_ITR_ENABLE 2
// I2S_MASTER_STATUS_INDEX_TX_UNDERFLOW 3
// I2S_MASTER_STATUS_INDEX_RX_OVERFLOW 4
// I2S_MASTER_STATUS_NONE 0

// reg i2s_master.rx_itr_num
// BW_I2S_MASTER_RX_ITR_NUM 8

// reg i2s_master.tx_fifo
// BW_I2S_MASTER_TX_FIFO 32

// reg i2s_master.rx_fifo
// BW_I2S_MASTER_RX_FIFO 32

// reg i2s_master.rx_fifo_valid_num
// BW_I2S_MASTER_RX_FIFO_VALID_NUM 7

#endif