#ifndef __ERVP_I2S_MASTER_MEMORYMAP_OFFSET_H__
#define __ERVP_I2S_MASTER_MEMORYMAP_OFFSET_H__



// total
#define BW_MMAP_OFFSET_ERVP_I2S_MASTER 6
#define ERVP_I2S_MASTER_ADDR_INTERVAL 8
#define BW_UNUSED_ERVP_I2S_MASTER 3
#define NUM_ERVP_I2S_MASTER_SUBMODULE 1

// submodule i2s_master
#define MMAP_SUBOFFSET_I2S_MASTER_CMD 0x0
#define MMAP_SUBOFFSET_I2S_MASTER_STATUS 0x8
#define MMAP_SUBOFFSET_I2S_MASTER_RX_ITR_NUM 0x10
#define MMAP_SUBOFFSET_I2S_MASTER_TX_FIFO 0x18
#define MMAP_SUBOFFSET_I2S_MASTER_RX_FIFO 0x20
#define MMAP_SUBOFFSET_I2S_MASTER_RX_FIFO_VALID_NUM 0x28

#define MMAP_OFFSET_I2S_MASTER_CMD (MMAP_SUBOFFSET_I2S_MASTER_CMD)
#define MMAP_OFFSET_I2S_MASTER_STATUS (MMAP_SUBOFFSET_I2S_MASTER_STATUS)
#define MMAP_OFFSET_I2S_MASTER_RX_ITR_NUM (MMAP_SUBOFFSET_I2S_MASTER_RX_ITR_NUM)
#define MMAP_OFFSET_I2S_MASTER_TX_FIFO (MMAP_SUBOFFSET_I2S_MASTER_TX_FIFO)
#define MMAP_OFFSET_I2S_MASTER_RX_FIFO (MMAP_SUBOFFSET_I2S_MASTER_RX_FIFO)
#define MMAP_OFFSET_I2S_MASTER_RX_FIFO_VALID_NUM (MMAP_SUBOFFSET_I2S_MASTER_RX_FIFO_VALID_NUM)

// reg i2s_master.cmd
#define BW_I2S_MASTER_CMD 8
#define I2S_MASTER_CMD_ENABLE_TX 1
#define I2S_MASTER_CMD_DISABLE_TX 2
#define I2S_MASTER_CMD_ENABLE_RX 4
#define I2S_MASTER_CMD_DISABLE_RX 8
#define I2S_MASTER_CMD_ENABLE_RX_ITR 16
#define I2S_MASTER_CMD_DISABLE_RX_ITR 32
#define I2S_MASTER_CMD_CLEAR_RX_ITR 64
#define I2S_MASTER_CMD_CLEAR_STATUS 128
#define I2S_MASTER_CMD_INDEX_ENABLE_TX 0
#define I2S_MASTER_CMD_INDEX_DISABLE_TX 1
#define I2S_MASTER_CMD_INDEX_ENABLE_RX 2
#define I2S_MASTER_CMD_INDEX_DISABLE_RX 3
#define I2S_MASTER_CMD_INDEX_ENABLE_RX_ITR 4
#define I2S_MASTER_CMD_INDEX_DISABLE_RX_ITR 5
#define I2S_MASTER_CMD_INDEX_CLEAR_RX_ITR 6
#define I2S_MASTER_CMD_INDEX_CLEAR_STATUS 7
#define I2S_MASTER_CMD_NONE 0

// reg i2s_master.status
#define BW_I2S_MASTER_STATUS 5
#define I2S_MASTER_STATUS_TX_ENABLE 1
#define I2S_MASTER_STATUS_RX_ENABLE 2
#define I2S_MASTER_STATUS_RX_ITR_ENABLE 4
#define I2S_MASTER_STATUS_TX_UNDERFLOW 8
#define I2S_MASTER_STATUS_RX_OVERFLOW 16
#define I2S_MASTER_STATUS_INDEX_TX_ENABLE 0
#define I2S_MASTER_STATUS_INDEX_RX_ENABLE 1
#define I2S_MASTER_STATUS_INDEX_RX_ITR_ENABLE 2
#define I2S_MASTER_STATUS_INDEX_TX_UNDERFLOW 3
#define I2S_MASTER_STATUS_INDEX_RX_OVERFLOW 4
#define I2S_MASTER_STATUS_NONE 0

// reg i2s_master.rx_itr_num
#define BW_I2S_MASTER_RX_ITR_NUM 8

// reg i2s_master.tx_fifo
#define BW_I2S_MASTER_TX_FIFO 32

// reg i2s_master.rx_fifo
#define BW_I2S_MASTER_RX_FIFO 32

// reg i2s_master.rx_fifo_valid_num
#define BW_I2S_MASTER_RX_FIFO_VALID_NUM 7

#endif