#ifndef __ERVP_DMA_MEMORYMAP_OFFSET_H__
#define __ERVP_DMA_MEMORYMAP_OFFSET_H__



// total
#define BW_MMAP_OFFSET_ERVP_DMA 6
#define ERVP_DMA_ADDR_INTERVAL 8
#define BW_UNUSED_ERVP_DMA 3
#define NUM_ERVP_DMA_SUBMODULE 1

// submodule dma
#define MMAP_SUBOFFSET_DMA_STATUS 0x0
#define MMAP_SUBOFFSET_DMA_START 0x8
#define MMAP_SUBOFFSET_DMA_PERIOD_INFO 0x10
#define MMAP_SUBOFFSET_DMA_SRC_ADDR 0x18
#define MMAP_SUBOFFSET_DMA_SRC_STRIDE 0x20
#define MMAP_SUBOFFSET_DMA_DST_ADDR 0x28
#define MMAP_SUBOFFSET_DMA_DST_STRIDE 0x30
#define MMAP_SUBOFFSET_DMA_LINE_INFO 0x38

#define MMAP_OFFSET_DMA_STATUS (MMAP_SUBOFFSET_DMA_STATUS)
#define MMAP_OFFSET_DMA_START (MMAP_SUBOFFSET_DMA_START)
#define MMAP_OFFSET_DMA_PERIOD_INFO (MMAP_SUBOFFSET_DMA_PERIOD_INFO)
#define MMAP_OFFSET_DMA_SRC_ADDR (MMAP_SUBOFFSET_DMA_SRC_ADDR)
#define MMAP_OFFSET_DMA_SRC_STRIDE (MMAP_SUBOFFSET_DMA_SRC_STRIDE)
#define MMAP_OFFSET_DMA_DST_ADDR (MMAP_SUBOFFSET_DMA_DST_ADDR)
#define MMAP_OFFSET_DMA_DST_STRIDE (MMAP_SUBOFFSET_DMA_DST_STRIDE)
#define MMAP_OFFSET_DMA_LINE_INFO (MMAP_SUBOFFSET_DMA_LINE_INFO)

// reg dma.status
#define BW_DMA_STATUS 3
#define DMA_STATUS_IDLE 0
#define DMA_STATUS_START_CHECK 1
#define DMA_STATUS_START_ACK 2
#define DMA_STATUS_BUSY 3
#define DMA_STATUS_WAIT_NEXT 4
#define DMA_STATUS_INDEX_START_CHECK 0
#define DMA_STATUS_INDEX_START_ACK 1
#define DMA_STATUS_INDEX_WAIT_NEXT 2

// reg dma.start
#define BW_DMA_START 1

// reg dma.period_info
#define BW_DMA_PERIOD_INFO 32

// reg dma.src_addr
#define BW_DMA_SRC_ADDR 32

// reg dma.src_stride
#define BW_DMA_SRC_STRIDE 32

// reg dma.dst_addr
#define BW_DMA_DST_ADDR 32

// reg dma.dst_stride
#define BW_DMA_DST_STRIDE 32

// reg dma.line_info
#define BW_DMA_LINE_INFO 32

// reg dma_state
#define BW_DMA_STATE 2
#define DMA_STATE_IDLE 0
#define DMA_STATE_RUN_ALL 1
#define DMA_STATE_RUN_WCH 2
#define DMA_STATE_WAIT 3
#define DMA_STATE_INDEX_RUN_ALL 0
#define DMA_STATE_INDEX_RUN_WCH 1

// reg dma_line_size
#define BW_DMA_LINE_SIZE 16

// reg dma_num_lines
#define BW_DMA_NUM_LINES 16

// reg dma_period
#define BW_DMA_PERIOD 16

#endif