#ifndef __ERVP_FUSE_BOX_MEMORYMAP_OFFSET_H__
#define __ERVP_FUSE_BOX_MEMORYMAP_OFFSET_H__



// total
#define BW_MMAP_OFFSET_ERVP_FUSE_BOX 5
#define ERVP_FUSE_BOX_ADDR_INTERVAL 8
#define BW_UNUSED_ERVP_FUSE_BOX 3
#define NUM_ERVP_FUSE_BOX_SUBMODULE 1

// submodule fuse_box
#define MMAP_SUBOFFSET_FUSE_BOX_CORE_CLOCK_CMD 0x0
#define MMAP_SUBOFFSET_FUSE_BOX_USER_CLOCK_CMD 0x8
#define MMAP_SUBOFFSET_FUSE_BOX_SYSTEM_CMD 0x10

#define MMAP_OFFSET_FUSE_BOX_CORE_CLOCK_CMD (MMAP_SUBOFFSET_FUSE_BOX_CORE_CLOCK_CMD)
#define MMAP_OFFSET_FUSE_BOX_USER_CLOCK_CMD (MMAP_SUBOFFSET_FUSE_BOX_USER_CLOCK_CMD)
#define MMAP_OFFSET_FUSE_BOX_SYSTEM_CMD (MMAP_SUBOFFSET_FUSE_BOX_SYSTEM_CMD)

// reg fuse_box.core_clock_cmd
#define BW_FUSE_BOX_CORE_CLOCK_CMD 32

// reg fuse_box.user_clock_cmd
#define BW_FUSE_BOX_USER_CLOCK_CMD 32

// reg fuse_box.system_cmd
#define BW_FUSE_BOX_SYSTEM_CMD 32

// reg clock_cmd
#define BW_CLOCK_CMD 3
#define CLOCK_CMD_WAKEUP 0
#define CLOCK_CMD_SLEEP 1
#define CLOCK_CMD_DISABLE 3
#define CLOCK_CMD_WFI 5

#endif