#ifndef __MUNOC_MEMORYMAP_H__
#define __MUNOC_MEMORYMAP_H__

#include "platform_info.h"
#include "munoc_memorymap_offset.h"

#define MMAP_SUBMODULE_INFO (NOC_CONTROLLER_BASEADDR+SUBMODULE_ADDR_MUNOC_INFO)
#define MMAP_SUBMODULE_ELOG (NOC_CONTROLLER_BASEADDR+SUBMODULE_ADDR_MUNOC_ELOG)
#define MMAP_SUBMODULE_CONTROLLER (NOC_CONTROLLER_BASEADDR+SUBMODULE_ADDR_MUNOC_CONTROLLER)

// submodule info
#define MMAP_INFO_VERSION0 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_INFO_VERSION0)
#define MMAP_INFO_VERSION1 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_INFO_VERSION1)
#define MMAP_INFO_VERSION2 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_INFO_VERSION2)
#define MMAP_INFO_VERSION3 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_INFO_VERSION3)
#define MMAP_INFO_CONFIG0 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_INFO_CONFIG0)
#define MMAP_INFO_CONFIG1 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_INFO_CONFIG1)
#define MMAP_INFO_NUM_MASTER (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_INFO_NUM_MASTER)
#define MMAP_INFO_NUM_SLAVE (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_INFO_NUM_SLAVE)
#define MMAP_INFO_SELF_ID (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_INFO_SELF_ID)

// submodule elog
#define MMAP_ELOG_COUNT (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_ELOG_COUNT)
#define MMAP_ELOG_VALID (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_ELOG_VALID)
#define MMAP_ELOG_RW (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_ELOG_RW)
#define MMAP_ELOG_ADDR (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_ELOG_ADDR)
#define MMAP_ELOG_MASTER (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_ELOG_MASTER)

// submodule controller
#define MMAP_CONTROLLER_NAME0 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_NAME0)
#define MMAP_CONTROLLER_NAME1 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_NAME1)
#define MMAP_CONTROLLER_NAME2 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_NAME2)
#define MMAP_CONTROLLER_NAME3 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_NAME3)
#define MMAP_CONTROLLER_NAME4 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_NAME4)
#define MMAP_CONTROLLER_NAME5 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_NAME5)
#define MMAP_CONTROLLER_NAME6 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_NAME6)
#define MMAP_CONTROLLER_NAME7 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_NAME7)
#define MMAP_CONTROLLER_TYPE0 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_TYPE0)
#define MMAP_CONTROLLER_TYPE1 (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_TYPE1)
#define MMAP_CONTROLLER_NODEID (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_NODEID)
#define MMAP_CONTROLLER_FNI_STATE (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_FNI_STATE)
#define MMAP_CONTROLLER_BNI_STATE (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_BNI_STATE)
#define MMAP_CONTROLLER_MONITOR_ENABLE (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_MONITOR_ENABLE)
#define MMAP_CONTROLLER_EXCLUDE (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_EXCLUDE)
#define MMAP_CONTROLLER_IP_TIMEOUT (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_IP_TIMEOUT)
#define MMAP_CONTROLLER_NOC_TIMEOUT (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_NOC_TIMEOUT)
#define MMAP_CONTROLLER_ROUTING_ERROR (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_ROUTING_ERROR)
#define MMAP_CONTROLLER_BANDWIDTH (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_BANDWIDTH)
#define MMAP_CONTROLLER_PROTOCOL_VIOLATION (NOC_CONTROLLER_BASEADDR+MMAP_OFFSET_CONTROLLER_PROTOCOL_VIOLATION)

// reg info.version0
// BW_INFO_VERSION0 32

// reg info.version1
// BW_INFO_VERSION1 32

// reg info.version2
// BW_INFO_VERSION2 32

// reg info.version3
// BW_INFO_VERSION3 32

// reg info.config0
// BW_INFO_CONFIG0 32

// reg info.config1
// BW_INFO_CONFIG1 32

// reg info.num_master
// BW_INFO_NUM_MASTER 32

// reg info.num_slave
// BW_INFO_NUM_SLAVE 32

// reg info.self_id
// BW_INFO_SELF_ID 32

// reg elog.count
// BW_ELOG_COUNT 32

// reg elog.valid
// BW_ELOG_VALID 32

// reg elog.rw
// BW_ELOG_RW 32

// reg elog.addr
// BW_ELOG_ADDR 32

// reg elog.master
// BW_ELOG_MASTER 32

// reg controller.name0
// BW_CONTROLLER_NAME0 32

// reg controller.name1
// BW_CONTROLLER_NAME1 32

// reg controller.name2
// BW_CONTROLLER_NAME2 32

// reg controller.name3
// BW_CONTROLLER_NAME3 32

// reg controller.name4
// BW_CONTROLLER_NAME4 32

// reg controller.name5
// BW_CONTROLLER_NAME5 32

// reg controller.name6
// BW_CONTROLLER_NAME6 32

// reg controller.name7
// BW_CONTROLLER_NAME7 32

// reg controller.type0
// BW_CONTROLLER_TYPE0 32

// reg controller.type1
// BW_CONTROLLER_TYPE1 32

// reg controller.nodeid
// BW_CONTROLLER_NODEID 32

// reg controller.fni_state
// BW_CONTROLLER_FNI_STATE 32

// reg controller.bni_state
// BW_CONTROLLER_BNI_STATE 32

// reg controller.monitor_enable
// BW_CONTROLLER_MONITOR_ENABLE 32

// reg controller.exclude
// BW_CONTROLLER_EXCLUDE 32

// reg controller.ip_timeout
// BW_CONTROLLER_IP_TIMEOUT 32

// reg controller.noc_timeout
// BW_CONTROLLER_NOC_TIMEOUT 32

// reg controller.routing_error
// BW_CONTROLLER_ROUTING_ERROR 32

// reg controller.bandwidth
// BW_CONTROLLER_BANDWIDTH 32

// reg controller.protocol_violation
// BW_CONTROLLER_PROTOCOL_VIOLATION 32

#endif