// ****************************************************************************
// ****************************************************************************
// Copyright SoC Design Research Group, All rights reserved.
// Electronics and Telecommunications Research Institute (ETRI)
// 
// THESE DOCUMENTS CONTAIN CONFIDENTIAL INFORMATION AND KNOWLEDGE
// WHICH IS THE PROPERTY OF ETRI. NO PART OF THIS PUBLICATION IS
// TO BE USED FOR ANY OTHER PURPOSE, AND THESE ARE NOT TO BE
// REPRODUCED, COPIED, DISCLOSED, TRANSMITTED, STORED IN A RETRIEVAL
// SYSTEM OR TRANSLATED INTO ANY OTHER HUMAN OR COMPUTER LANGUAGE,
// IN ANY FORM, BY ANY MEANS, IN WHOLE OR IN PART, WITHOUT THE
// COMPLETE PRIOR WRITTEN PERMISSION OF ETRI.
// ****************************************************************************
// 2019-04-12
// Sukho Lee (shlee99@etri.re.kr)
// ****************************************************************************
// ****************************************************************************

#ifndef __TEI_CONTROLLER_MEMORYMAP_H__
#define __TEI_CONTROLLER_MEMORYMAP_H__

// bio controller
#define BW_MMAP_OFFSET_TEI_CONTROLLER (7)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEMP_OFF  (0x0)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEMP      (0x4)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_DC_DC_BYPASS     (0x8)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_DC_DC            (0xc)

#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_ADC_TEMP_SENSOR  (0x10)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_ADC_TEMP         (0x14)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_ADC_TEMP_SPARE   (0x18)

#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_VREF_CTRL (0x20)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_VREF_OP            (0x24)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_F_REF_H_OP         (0x28)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_F_REF_L_OP         (0x2c)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_CONVERSION_FRE_OP  (0x30)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_CTRL_PART_FRE_OP   (0x34)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_TP_SELECT          (0x38)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_RESET     (0x3c)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_DELAY     (0x40)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_BIAS      (0x44)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_VCO       (0x48)
#define MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_CP        (0x4c)

#define MMAP_OFFSET_TEI_CONTROLLER_TEMP_OFF (MMAP_SUBOFFSET_TEI_CONTROLLER_TEMP_OFF)
#define MMAP_OFFSET_TEI_CONTROLLER_TEMP     (MMAP_SUBOFFSET_TEI_CONTROLLER_TEMP)
#define MMAP_OFFSET_TEI_CONTROLLER_DC_DC_BYPASS    (MMAP_SUBOFFSET_TEI_CONTROLLER_DC_DC_BYPASS)
#define MMAP_OFFSET_TEI_CONTROLLER_DC_DC           (MMAP_SUBOFFSET_TEI_CONTROLLER_DC_DC)

#define MMAP_OFFSET_TEI_CONTROLLER_ADC_TEMP_OFF       (MMAP_SUBOFFSET_TEI_CONTROLLER_ADC_TEMP_OFF)
#define MMAP_OFFSET_TEI_CONTROLLER_ADC_TEMP           (MMAP_SUBOFFSET_TEI_CONTROLLER_ADC_TEMP)
#define MMAP_OFFSET_TEI_CONTROLLER_DC_DC_BYPASS   (MMAP_SUBOFFSET_TEI_CONTROLLER_DC_DC_BYPASS)
#define MMAP_OFFSET_TEI_CONTROLLER_DC_DC          (MMAP_SUBOFFSET_TEI_CONTROLLER_DC_DC)

#define MMAP_OFFSET_TEI_CONTROLLER_TEST_ADC_TEMP_SENSOR_OP (MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_ADC_TEMP_SENSOR)
#define MMAP_OFFSET_TEI_CONTROLLER_TEST_ADC_TEMP_OP     (MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_ADC_TEMP)
#define MMAP_OFFSET_TEI_CONTROLLER_TEST_ADC_TEMP_SPARE     (`MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_ADC_TEMP_SPARE)


#define MMAP_OFFSET_TEI_CONTROLLER_TEST_DC_DC_VREF_CTRL (MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_VREF_CTRL)
#define MMAP_OFFSET_TEI_CONTROLLER_TEST_DC_DC_VREF_OP   (`MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_VREF_OP)
#define MMAP_OFFSET_TEI_CONTROLLER_TEST_DC_DC_F_REF_H_OP   (`MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_F_REF_H_OP)
#define MMAP_OFFSET_TEI_CONTROLLER_TEST_DC_DC_F_REF_L_OP   (`MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_F_REF_L_OP)
#define MMAP_OFFSET_TEI_CONTROLLER_TEST_DC_DC_CONVERSION_FRE_OP   (`MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_CONVERSION_FRE_OP)
#define MMAP_OFFSET_TEI_CONTROLLER_TEST_DC_DC_CTRL_PART_FRE_OP   (`MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_CTRL_PART_FRE_OP)
#define MMAP_OFFSET_TEI_CONTROLLER_TEST_DC_DC_RESET  (MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_RESET)
#define MMAP_OFFSET_TEI_CONTROLLER_TEST_DC_DC_DELAY (MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_DELAY)
#define MMAP_OFFSET_TEI_CONTROLLER_TEST_DC_DC_BIAS    (MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_BIAS)
#define MMAP_OFFSET_TEI_CONTROLLER_TEST_DC_DC_VCO    (MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_VCO)
#define MMAP_OFFSET_TEI_CONTROLLER_TEST_DC_DC_CP    (MMAP_SUBOFFSET_TEI_CONTROLLER_TEST_DC_DC_CP)

#endif
